name: Deploy to Coolify

on:
  workflow_run:
    workflows: ["Update Articles File"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Add additional checks to ensure this only runs on main branch pushes
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'
    environment: production
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl --request GET --url '${{ secrets.COOLIFY_WEBHOOK_URL }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}'
